services:
  nginx:
    image: nginx:1.25-alpine
    volumes:
      - ./nginx-dev.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    networks:
      - api
      - payment-processor
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "0.15"
    #       memory: "15MB"

  api1: &api
    build: 
      context: .
      dockerfile: api/build/Dockerfile.dev
    volumes:
      - ./:/app
    networks:
      - api
      - payment-processor
    depends_on:
      - redis
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "0.25"
    #       memory: "75MB"

  api2:
    <<: *api

  health: 
    build: 
      context: .
      dockerfile: health/build/Dockerfile.dev
    volumes:
      - ./:/app
    networks:
      - api
      - payment-processor
    depends_on:
      - redis
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "0.10"
    #       memory: "10MB"

  payment: 
    build: 
      context: .
      dockerfile: payment/build/Dockerfile.dev
    volumes:
      - ./:/app
    networks:
      - api
      - payment-processor
    depends_on:
      - redis
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "0.50"
    #       memory: "190MB"

  redis:
    image: "redis:alpine"
    volumes:
      - redis-data:/data
    networks:
      - api
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "0.35"
    #       memory: "35MB"

volumes:
  redis-data:

networks:
  api:
    driver: bridge
  payment-processor:
    external: true